spring.application.name=farmsPotLoanApp


spring.datasource.url=jdbc:mysql://127.0.0.1:3306/farmspot_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=farmsPot
spring.datasource.password=YourNewRealPassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oluwaseunpu@gmail.com
spring.mail.password=zzqlxaxkdehrsvms 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

